version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_URL=http://frontend:80
    ports:
      - "5000:5000"  
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://backend:5000
    ports:
      - "80:80" 
    networks:
      - app-network

networks:
  app-network:
