version: '3.8'

services:
  proxy:
    image: todjalawregistry.azurecr.io/proxy:latest
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    image: todjalawregistry.azurecr.io/backend:latest
    container_name: backend
    expose:
      - "5000"
      
  frontend:
    image: todjalawregistry.azurecr.io/frontend:latest
    container_name: frontend
    expose:
      - "80"
