version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    image: todjalawregistry.azurecr.io/backend:latest
    container_name: backend
    expose:
      - "5000"
      
  frontend:
    image: todjalawregistry.azurecr.io/frontend:latest
    container_name: frontend
    expose:
      - "80"
